package com.hp.exceptions.boot;

import java.awt.AWTException;
import java.awt.FontFormatException;
import java.awt.datatransfer.MimeTypeParseException;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.geom.NoninvertibleTransformException;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.lang.instrument.IllegalClassFormatException;
import java.lang.instrument.UnmodifiableClassException;
import java.net.URISyntaxException;
import java.rmi.activation.ActivationException;
import java.rmi.server.ServerNotActiveException;
import java.security.GeneralSecurityException;
import java.security.acl.AclNotFoundException;
import java.security.acl.LastOwnerException;
import java.security.cert.CertificateException;
import java.sql.SQLException;
import java.util.TooManyListenersException;
import java.util.concurrent.BrokenBarrierException;
import java.util.concurrent.TimeoutException;
import java.util.prefs.BackingStoreException;
import java.util.zip.DataFormatException;

import javax.management.BadAttributeValueExpException;
import javax.management.BadBinaryOpValueExpException;
import javax.management.BadStringOperationException;
import javax.management.InvalidApplicationException;
import javax.management.JMException;
import javax.management.modelmbean.InvalidTargetObjectTypeException;
import javax.naming.NamingException;
import javax.print.PrintException;
import javax.script.ScriptException;
import javax.security.auth.DestroyFailedException;
import javax.security.auth.RefreshFailedException;
import javax.security.auth.callback.UnsupportedCallbackException;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiUnavailableException;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.text.BadLocationException;
import javax.swing.tree.ExpandVetoException;
import javax.transaction.xa.XAException;
import javax.xml.crypto.KeySelectorException;
import javax.xml.crypto.MarshalException;
import javax.xml.crypto.URIReferenceException;
import javax.xml.crypto.dsig.TransformException;
import javax.xml.crypto.dsig.XMLSignatureException;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.soap.SOAPException;
import javax.xml.stream.XMLStreamException;
import javax.xml.transform.TransformerException;
import javax.xml.xpath.XPathException;

import org.ietf.jgss.GSSException;
import org.omg.CORBA.portable.ApplicationException;
import org.omg.CORBA.portable.RemarshalException;
import org.xml.sax.SAXException;

import com.hp.exceptions.events.CreatEvents;

public class EventRunner {

	public static void main(String[] args) throws AclNotFoundException, ActivationException, AWTException, BackingStoreException, BadAttributeValueExpException, BadLocationException, XPathException, XMLStreamException, XMLSignatureException, XAException, URISyntaxException, URIReferenceException, UnsupportedFlavorException, UnsupportedCallbackException, UnmodifiableClassException, UnsupportedAudioFileException, TransformerException, TransformException, TooManyListenersException, TimeoutException, SQLException, SOAPException, ServerNotActiveException, ScriptException, SAXException, RemarshalException, RefreshFailedException, ReflectiveOperationException, PrinterException, PrintException, ApplicationException, BadBinaryOpValueExpException, BadStringOperationException, BrokenBarrierException, MimeTypeParseException, MidiUnavailableException, DataFormatException, CloneNotSupportedException, DatatypeConfigurationException, DestroyFailedException, MarshalException, LineUnavailableException, LastOwnerException, KeySelectorException, JMException, IOException, InvalidTargetObjectTypeException, InvalidMidiDataException, InvalidApplicationException, ExpandVetoException, InterruptedException, IllegalClassFormatException, GSSException, GeneralSecurityException, FontFormatException, NoninvertibleTransformException, NamingException {
		CreatEvents events=new CreatEvents();
		
		events.joy();
		events.jaideep();
		events.jaggi();
		events.jagadeesh();
		events.allagi();
		events.anju();
		events.amul();
		events.jaggu();
		events.appu();
		events.ammu();
		events.muddu();
		events.bangari();
		events.captain();
		events.power();
		events.jeevs();
		events.peddu();
		events.sneha();
		events.sani();
		events.uttu();
		events.yashu();
		events.bhabi();
		events.dada();
		events.amma();
		events.appa();
		events.breath();
		events.viju();
		events.anna();
		events.chandi();
		events.anarkali();
		events.champakali();
		events.jamoon();
		events.burfee();
		events.palav();
		events.dose();
		events.puliyogare();
		events.dosta();
		System.out.println("----------------------------------------");
		events.deepti();
		events.chaitra();
		events.monu();
		events.deeksha();
		events.akka();
		events.pinki();
		events.minki();
		events.chinki();
		events.ranna();
		events.bangara();
		events.darling();
		events.veenu();
		events.malli();
		events.layse();
		events.action();
		events.nandu();
		events.manvi();
		events.kavi();
		events.kencha();
		events.kempi();
		events.hampi();
		events.dummi();
		events.kaddi();
		events.nagu();
		events.rakshu();
		events.charish();
		events.mava();
		events.mane();
		events.atte();
		events.avva();
		events.ajji();
		events.ajja();
		events.comit();
		events.darshu();
		events.dham();
		events.water();
		System.out.println("--------------------------------------------------");
		events.jacky();
		events.pavan();
		events.mahi();
		events.manoj();
		events.ambu();
		events.panda();
		events.putani();
		events.chintu();
		events.sonu();
		events.deekshu();
		events.mamma();
		events.ammamma();
		events.raksha();
		events.sandya();
		events.annaporna();
		events.pillo();
		events.bag();
		events.love();
		events.sannu();
		events.appaji();
		events.doddu();
		events.guddu();
		events.gunda();
		events.pushi();
		events.paddu();
		events.akash();
		events.suju();
		events.spoo();
		events.goshal();
		events.shreya();
		
	}

}
